### ISSUE TITLE
Game crashes every time at the same train position

### ISSUE THREAD

**Issue by Livedeath2k** [xmnovotny/VoxelTycoon-AdvancedPathfinder#5] opened 2021-08-29 17:44 UTC
Hi.
I use your mods and i get a game crash everytime my train travels to a specific position on the map.
Can you please check if one your mod have a bug?
Because the other mods i use so far are running smooth before i added your mods.
I added the save as compressed zip file.
Thank you :-)

[Player.log](https://github.com/xmnovotny/VoxelTycoon-AdvancedPathfinder/files/7072967/Player.log)
[yp5kyg0oo2c.zip](https://github.com/xmnovotny/VoxelTycoon-AdvancedPathfinder/files/7072961/yp5kyg0oo2c.zip)

**Comment by xmnovotny** [comment] 2021-08-30 18:55
Thank you for detailed info. Confirming that bug, so now I will investigate the cause and then it will be fixed in the next version as soon as possible.

**Comment by xmnovotny** [comment] 2021-08-30 20:52
Ok, one "your" bug solved, another two serious found :-)

**Comment by Livedeath2k** [comment] 2021-08-31 10:47
Nice.Oh 2 more bugs found?Interesting.Thank you for trying to fix them. ☺️Am 30.08.2021 22:52 schrieb xmnovotny ***@***.***>:
Ok, one "your" bug solved, another two serious found :-)

**Comment by xmnovotny** [comment] 2021-09-01 19:20
Hopefully everything is fixed now. You can try.

**Closed as completed by xmnovotny** 2021-09-01 19:20 UTC
Labels: bug
